
import React, { useState, useEffect } from 'react';
import { DashboardLayout } from '../../types';

interface NarrativeReportModalProps {
  layout: DashboardLayout;
  onClose: () => void;
}

const NarrativeReportModal: React.FC<NarrativeReportModalProps> = ({ layout, onClose }) => {
  const [report, setReport] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(true);

  useEffect(() => {
    // Mocking an AI report generation based on the layout
    const generate = async () => {
      await new Promise(r => setTimeout(r, 2000));
      const text = `
# Executive Analytical Narrative: ${layout.name}
**Date:** ${new Date().toLocaleDateString()}
**Version:** ${layout.version}.0

## 1. Contextual Overview
This report synthesizes data from ${layout.components.length} primary analytical vectors. Current operational state indicates stable performance with emerging opportunities in high-growth segments.

## 2. Key Findings
- **Forecast Stability:** Primary metrics show a 94% confidence interval for the next quarter.
- **Segment Anomaly:** High-value transactions identified in SMB clusters suggest a shift in purchasing patterns.

## 3. Recommended Strategic Pivot
Shift budget allocation from traditional search to retargeting modules to capture a 12% anticipated efficiency gain.

---
*Generated by Tambo AI Autonomous Reporting Layer*
      `;
      setReport(text);
      setIsGenerating(false);
    };
    generate();
  }, [layout]);

  return (
    <div className="fixed inset-0 z-[100] bg-slate-900/60 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-white w-full max-w-2xl max-h-[90vh] rounded-3xl shadow-2xl overflow-hidden flex flex-col border border-white">
        <div className="p-6 border-b border-slate-100 flex items-center justify-between bg-slate-50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-rose-100 text-rose-600 rounded-xl flex items-center justify-center">
              <i className="fa-solid fa-file-invoice"></i>
            </div>
            <div>
              <h3 className="text-lg font-black text-slate-900">Executive Narrative</h3>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Autonomous Reporting Module</p>
            </div>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600"><i className="fa-solid fa-xmark"></i></button>
        </div>

        <div className="flex-1 overflow-y-auto p-8 prose prose-slate max-w-none">
          {isGenerating ? (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <div className="w-12 h-12 border-4 border-rose-100 border-t-rose-500 rounded-full animate-spin mb-4"></div>
              <p className="text-xs font-bold text-slate-500 uppercase tracking-widest">Compiling Narrative Artifacts...</p>
            </div>
          ) : (
            <div className="whitespace-pre-wrap font-sans text-slate-700 leading-relaxed text-sm">
              {report}
            </div>
          )}
        </div>

        <div className="p-6 border-t border-slate-100 bg-slate-50 flex justify-end gap-3">
          <button className="px-4 py-2 text-xs font-bold text-slate-600 hover:bg-slate-200 rounded-xl transition-all">
            <i className="fa-solid fa-print mr-2"></i> Print PDF
          </button>
          <button className="px-6 py-2 bg-slate-900 text-white text-xs font-black uppercase tracking-widest rounded-xl shadow-lg hover:shadow-xl hover:scale-105 active:scale-95 transition-all">
            <i className="fa-solid fa-file-export mr-2"></i> Push to Slack
          </button>
        </div>
      </div>
    </div>
  );
};

export default NarrativeReportModal;
